Models/UserRegistration.cs
namespace TimeTracking_Ui
{
    public class UserRegistration
    {
        public int Id { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public DateTime UpdatedDateTime { get; set; }
        public string? Name { get; set; }
        public string? EmailAddress { get; set; }
        public string?  FirstName { get; set; }
        public string? LastName { get; set; }
        public int RoleId { get; set; }
        public string? Password { get; set; }
        public  bool IsActive { get; set; }
    }
}

Controllers/UserRegistrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace TimeTracking_Ui.Controllers
{
    
    public class UserRegistrationController : Controller
    {
        //GET 
        public ActionResult Index()
        {

            ViewBag.message = "WELCOME";
            
            return View();

        }

        [HttpPost]
      
        public IActionResult SaveUser(UserRegistration userRegistration)
        {

            try
            {
                DatabaseService databaseService = new DatabaseService();

                var numberOfRecordsUpdated = databaseService.SaveUser(userRegistration);

                return Ok(numberOfRecordsUpdated);

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        
        //GET: UserRegistrationController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: UserRegistrationController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: UserRegistrationController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: UserRegistrationController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Views/UserRegistration/Index.cshtml
@model TimeTracking_Ui.UserRegistration
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br></br><br></br>
<h2>WELCOME...</h2>

<br></br>
   <div class="row">

    <form class="row g-3" asp-controller="UserRegistration" asp-action="SaveUser" method="post">
        <div class="col-md-6">
            <label asp-for="Id" class="form-label">ID</label>
            <input asp-for="Id" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
            <label asp-for="CreatedDateTime" class="form-label">CreatedDateTime</label>
            <input asp-for="CreatedDateTime" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
          <label asp-for="UpdatedDateTime" class="form-label">UpdatedDateTime</label>
            <input asp-for="UpdatedDateTime" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
           <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control" id="inputId">
        </div>

        <div class="col-md-6">
            <label asp-for="EmailAddress" class="form-label">EmailAddress</label>
            <input asp-for="EmailAddress" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
           <label asp-for="FirstName" class="form-label">FirstName</label>
            <input asp-for="FirstName" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
           <label asp-for="LastName" class="form-label">LastName</label>
            <input asp-for="LastName" class="form-control" id="inputId">
       
        </div>
        <div class="col-md-6">
           <label asp-for="RoleId" class="form-label">RoleId</label>
            <input asp-for="RoleId" class="form-control" id="inputId">
        
        </div>
        <div class="col-md-6">
           <label asp-for="Password" class="form-label">Password</label>
            <input asp-for="Password" class="form-control" id="inputId">
       
        </div><br></br><br></br>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Register</button>
        </div>
    </form>
</div>

 