Models/UserDetails.cs
namespace TimeTracking_Ui.Models
{
    public class UserDetails
    {
        public int Id { get; set; }
        public DateTime CreatedDateTime { get; set; }
        public DateTime UpdatedDateTime { get; set; }
        public string? Name { get; set; }
        public string? EmailAddress { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public int RoleId { get; set; }
        public string? Password { get; set; }
    }
}

Controllers/UserDetailsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TimeTracking_Ui.Controllers
{
    public class UserDetailsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetUser(int id)
        {
            try
            {
                DatabaseService databaseService = new DatabaseService();

                var listOfUsers = databaseService.GetUser(id);

                return Ok(listOfUsers);

            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        [HttpPost]
        public IActionResult UpdateUser(UserRegistration userRegistration)
        {
            try
            {
                DatabaseService databaseService = new DatabaseService();
                var updatedUser = databaseService.UpdateUser(userRegistration);
                return Ok(updatedUser);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
        [HttpGet]
        public IActionResult DeleteUser(int id)
        {
            try
            {
                DatabaseService databaseService = new DatabaseService();
                var updatedUser = databaseService.DeleteUser(id);
                return Ok(updatedUser);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }
}

Views/UserDetails/Index.cshtml
@model TimeTracking_Ui.Models.UserDetails
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br></br><br></br>
<h3>Check the UserDetails.....</h3>


<div class="row">

    <form class="row g-3" asp-controller="UserDetails" asp-action="GetUser" method="get">
        <div class="col-md-6">
            <label asp-for="Id" class="form-label">ID</label>
            <input asp-for="Id" class="form-control" id="inputId">
        </div>
        <br></br><br></br>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">GetUser</button>
        </div>
    </form>
</div>


<h3>Update UserDetails.....</h3>

<div class="row">

    <form class="row g-3" asp-controller="UserDetails" asp-action="UpdateUser" method="post">
        <div class="col-md-6">
            <label asp-for="Id" class="form-label">ID</label>
            <input asp-for="Id" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
            <label asp-for="CreatedDateTime" class="form-label">CreatedDateTime</label>
            <input asp-for="CreatedDateTime" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
          <label asp-for="UpdatedDateTime" class="form-label">UpdatedDateTime</label>
            <input asp-for="UpdatedDateTime" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
           <label asp-for="Name" class="form-label">Name</label>
            <input asp-for="Name" class="form-control" id="inputId">
        </div>

        <div class="col-md-6">
            <label asp-for="EmailAddress" class="form-label">EmailAddress</label>
            <input asp-for="EmailAddress" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
           <label asp-for="FirstName" class="form-label">FirstName</label>
            <input asp-for="FirstName" class="form-control" id="inputId">
        </div>
        <div class="col-md-6">
           <label asp-for="LastName" class="form-label">LastName</label>
            <input asp-for="LastName" class="form-control" id="inputId">
       
        </div>
        <div class="col-md-6">
           <label asp-for="RoleId" class="form-label">RoleId</label>
            <input asp-for="RoleId" class="form-control" id="inputId">
        </div>
         
        <div class="col-md-6">
           <label asp-for="Password" class="form-label">Password</label>
            <input asp-for="Password" class="form-control" id="inputId">
       
        </div>
        <br></br><br></br>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">UpdateUser</button>
        </div>
    </form>
</div>


<h3>Delete User.....</h3>



<div class="row">

    <form class="row g-3" asp-controller="UserDetails" asp-action="DeleteUser" method="get">
        <div class="col-md-6">
            <label asp-for="Id" class="form-label">ID</label>
            <input asp-for="Id" class="form-control" id="inputId">
        </div>       
        <div class="col-12">
            <button type="submit" class="btn btn-primary">DeleteUser</button>
        </div>
    </form>
</div>